/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9-dev */

#include "bowie.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(bowie_Mag, bowie_Mag, AUTO)


PB_BIND(bowie_Quat, bowie_Quat, AUTO)


PB_BIND(bowie_Data, bowie_Data, AUTO)




