# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: proto/bowie.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass

import betterproto


class Finger(betterproto.Enum):
    none = 0
    pinky = 1
    ring = 2
    middle = 3
    index = 4
    thumb = 5


@dataclass(eq=False, repr=False)
class Mag(betterproto.Message):
    seconds: int = betterproto.int32_field(1)
    nanoseconds: int = betterproto.int32_field(2)
    x: float = betterproto.float_field(3)
    y: float = betterproto.float_field(4)
    z: float = betterproto.float_field(5)


@dataclass(eq=False, repr=False)
class Quat(betterproto.Message):
    seconds: int = betterproto.int32_field(1)
    nanoseconds: int = betterproto.int32_field(2)
    x: float = betterproto.float_field(3)
    y: float = betterproto.float_field(4)
    z: float = betterproto.float_field(5)
    w: float = betterproto.float_field(6)
    accuracy: float = betterproto.float_field(7)


@dataclass(eq=False, repr=False)
class Data(betterproto.Message):
    index: int = betterproto.int32_field(1)
    finger: "Finger" = betterproto.enum_field(2)
    link: int = betterproto.int32_field(3)
    sensor_id: int = betterproto.int32_field(4)
    mag: "Mag" = betterproto.message_field(5)
    quat: "Quat" = betterproto.message_field(6)
