/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9-dev */

#ifndef PB_BOWIE_BOWIE_PB_H_INCLUDED
#define PB_BOWIE_BOWIE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _bowie_Finger {
    bowie_Finger_none = 0,
    bowie_Finger_pinky = 1,
    bowie_Finger_ring = 2,
    bowie_Finger_middle = 3,
    bowie_Finger_index = 4,
    bowie_Finger_thumb = 5
} bowie_Finger;

/* Struct definitions */
typedef struct _bowie_Mag {
    int32_t seconds;
    int32_t nanoseconds;
    float x;
    float y;
    float z;
} bowie_Mag;

typedef struct _bowie_Quat {
    int32_t seconds;
    int32_t nanoseconds;
    float x;
    float y;
    float z;
    float w;
    float accuracy;
} bowie_Quat;

typedef struct _bowie_Data {
    int32_t index;
    bowie_Finger finger;
    int32_t link;
    int32_t sensor_id;
    bool has_mag;
    bowie_Mag mag;
    bool has_quat;
    bowie_Quat quat;
} bowie_Data;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _bowie_Finger_MIN bowie_Finger_none
#define _bowie_Finger_MAX bowie_Finger_thumb
#define _bowie_Finger_ARRAYSIZE ((bowie_Finger)(bowie_Finger_thumb+1))



#define bowie_Data_finger_ENUMTYPE bowie_Finger


/* Initializer values for message structs */
#define bowie_Mag_init_default                   {0, 0, 0, 0, 0}
#define bowie_Quat_init_default                  {0, 0, 0, 0, 0, 0, 0}
#define bowie_Data_init_default                  {0, _bowie_Finger_MIN, 0, 0, false, bowie_Mag_init_default, false, bowie_Quat_init_default}
#define bowie_Mag_init_zero                      {0, 0, 0, 0, 0}
#define bowie_Quat_init_zero                     {0, 0, 0, 0, 0, 0, 0}
#define bowie_Data_init_zero                     {0, _bowie_Finger_MIN, 0, 0, false, bowie_Mag_init_zero, false, bowie_Quat_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define bowie_Mag_seconds_tag                    1
#define bowie_Mag_nanoseconds_tag                2
#define bowie_Mag_x_tag                          3
#define bowie_Mag_y_tag                          4
#define bowie_Mag_z_tag                          5
#define bowie_Quat_seconds_tag                   1
#define bowie_Quat_nanoseconds_tag               2
#define bowie_Quat_x_tag                         3
#define bowie_Quat_y_tag                         4
#define bowie_Quat_z_tag                         5
#define bowie_Quat_w_tag                         6
#define bowie_Quat_accuracy_tag                  7
#define bowie_Data_index_tag                     1
#define bowie_Data_finger_tag                    2
#define bowie_Data_link_tag                      3
#define bowie_Data_sensor_id_tag                 4
#define bowie_Data_mag_tag                       5
#define bowie_Data_quat_tag                      6

/* Struct field encoding specification for nanopb */
#define bowie_Mag_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    seconds,           1) \
X(a, STATIC,   SINGULAR, INT32,    nanoseconds,       2) \
X(a, STATIC,   SINGULAR, FLOAT,    x,                 3) \
X(a, STATIC,   SINGULAR, FLOAT,    y,                 4) \
X(a, STATIC,   SINGULAR, FLOAT,    z,                 5)
#define bowie_Mag_CALLBACK NULL
#define bowie_Mag_DEFAULT NULL

#define bowie_Quat_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    seconds,           1) \
X(a, STATIC,   SINGULAR, INT32,    nanoseconds,       2) \
X(a, STATIC,   SINGULAR, FLOAT,    x,                 3) \
X(a, STATIC,   SINGULAR, FLOAT,    y,                 4) \
X(a, STATIC,   SINGULAR, FLOAT,    z,                 5) \
X(a, STATIC,   SINGULAR, FLOAT,    w,                 6) \
X(a, STATIC,   SINGULAR, FLOAT,    accuracy,          7)
#define bowie_Quat_CALLBACK NULL
#define bowie_Quat_DEFAULT NULL

#define bowie_Data_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    index,             1) \
X(a, STATIC,   SINGULAR, UENUM,    finger,            2) \
X(a, STATIC,   SINGULAR, INT32,    link,              3) \
X(a, STATIC,   SINGULAR, INT32,    sensor_id,         4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  mag,               5) \
X(a, STATIC,   OPTIONAL, MESSAGE,  quat,              6)
#define bowie_Data_CALLBACK NULL
#define bowie_Data_DEFAULT NULL
#define bowie_Data_mag_MSGTYPE bowie_Mag
#define bowie_Data_quat_MSGTYPE bowie_Quat

extern const pb_msgdesc_t bowie_Mag_msg;
extern const pb_msgdesc_t bowie_Quat_msg;
extern const pb_msgdesc_t bowie_Data_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define bowie_Mag_fields &bowie_Mag_msg
#define bowie_Quat_fields &bowie_Quat_msg
#define bowie_Data_fields &bowie_Data_msg

/* Maximum encoded size of messages (where known) */
#define BOWIE_BOWIE_PB_H_MAX_SIZE                bowie_Data_size
#define bowie_Data_size                          123
#define bowie_Mag_size                           37
#define bowie_Quat_size                          47

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
